name: Job Scraper

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 8AM CST (13 UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright pandas
          playwright install

      - name: Run job scraper
        run: python job_scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add job_postings.csv
          git commit -m "Update job postings" || echo "No changes"
          git push
