name: Run Job Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Every day at 12:00 UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install playwright pandas
        playwright install --with-deps chromium

    - name: Run Dealer Scraper
      run: python job_scraper.py

    - name: Run Indeed Scraper
      run: python indeed_scraper.py

    - name: Upload Dealer CSV
      uses: actions/upload-artifact@v4
      with:
        name: dealer-postings
        path: job_postings.csv

    - name: Upload Indeed CSV
      uses: actions/upload-artifact@v4
      with:
        name: indeed-postings
        path: indeed_postings.csv
