name: run-scraper

on:
  workflow_dispatch:         # allows manual run in GitHub UI
  schedule:
    - cron: '0 13 * * *'     # daily at 8AM Central (13:00 UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run job scraper
        run: python job_scraper.py

      - name: Commit and push job_postings.csv to `data` branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -B data
          git add job_postings.csv
          git commit -m "Update job postings" || echo "No changes to commit"
          git push origin data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
