name: Job Scraper

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 8AM CST (13 UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright pandas
          playwright install

      - name: Run job scraper
        run: python job_scraper.py

- name: Commit and push results to `data` branch
  run: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git checkout -B data
    git add job_postings.csv
    git commit -m "Update job postings" || echo "No changes"
    git push origin data
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
